### ISSUE TITLE
Terminal error when trying to use create-react-styleguide

### ISSUE THREAD

**Issue by OGHP** [zillow/create-react-styleguide#23]
▶ npx create-react-styleguide new @zillow/zrs-foundation
? author: 
? homepage: 
  create .gitignore
  create CONTRIBUTING.md
  create README.md
  create babel.config.js
  create docs/introduction.md
  create jest.config.js
  create package.json
  create styleguide.config.js
  create jest.config.js
  create src/__tests__/index.test.js
  create src/components/Button/Button.jsx
  create src/components/Button/Button.md
  create src/components/Button/index.js
  create src/index.js
  create src/styleguidist/ThemeWrapper.jsx
  create src/themes/Bootstrap/index.js
  create src/themes/index.js
  create styleguide.config.js
  create .eslintignore
  create .eslintrc
✔ Initing Git repo
✔ Installing react@^16.7.0, react-dom@^16.7.0, create-react-styleguide, babel-preset-zillow@^4.0.3, husky@^1.3.1, react-test-renderer@^16.7.0, eslint-plugin-zillow@^3.1.0, eslint-plugin-jest@^22.2.1, babel-plugin-styled-components@^1.10.0 and jest-styled-components@^6.3.1
✔ Installing prop-types@^15.6.2 and styled-components@^4.1.3
✖ Adding initial commit in Git repo
Command failed: git commit -m "Initial commit from create-react-styleguide v4.0.6"
husky > pre-commit (node v10.15.3)

> @zillow/zrs-foundation@1.0.0 eslint path/to/my/crs-project
> create-react-styleguide script eslint

path/to/my/crs-project/src/__tests__/index.test.js
  3:38  error  Unable to resolve path to module '../components/Button/Button'  zillow/import/no-unresolved

path/to/my/crs-project/src/components/Button/index.js
  1:25  error  Unable to resolve path to module './Button'  zillow/import/no-unresolved

✖ 2 problems (2 errors, 0 warnings)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @zillow/zrs-foundation@1.0.0 eslint: `create-react-styleguide script eslint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @zillow/zrs-foundation@1.0.0 eslint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     path/to/my/crs-project/.npm/_logs/2019-07-01T23_45_43_583Z-debug.log
husky > pre-commit hook failed (add --no-verify to bypass)

**Comment by stonebk** [comment]
This looks like it is an issue with `eslint-plugin-zillow`, specifically the changes to this file:
https://github.com/zillow/javascript/commit/3628fb8#diff-0f8047a836e1149dadbd89338247116a

**Comment by stonebk** [comment]
Workaround: revert to `npm i eslint-plugin-zillow@3.2.0`

**Comment by stonebk** [comment]
Fixed in `create-react-styleguide@5.0.0`
