### ISSUE TITLE
Cannot create a class based component

### ISSUE THREAD

**Issue by jeffscottward** [zillow/create-react-styleguide#7]
Only stateless components seem to render

`const Button = props => <button {...props} />;`

```
import React from 'react';
export default class Test {
    render() {
        return (
            <div>Hello</div>
        );
    }
}
```

does not work. compiles but fails silently.
@stonebk

**Comment by stonebk** [comment]
Hey @jeffscottward,

It looks like you may be missing the extends. Can you try this:
```
export default class Test extends React.Component {
```

**Comment by jeffscottward** [comment]
Yup confirmed. This works. Closing
